apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    service: forgeservice
  name: forgeservice
spec:
  replicas: 1
  selector:
    matchLabels:
      service: forgeservice
  strategy: {}
  template:
    metadata:
      labels:
        service: forgeservice
    spec:
      containers:
      - env:
        - name: FORGESERVICE_MONGOCONNECTION
          value: mongodb://mongo/forge
        - name: FORGESERVICE_SMELTERCONNECTION
          value: http://smelterservice:8081
        image: gcr.io/PROJECT_ID/forgeservice:VERSION
        imagePullPolicy: ""
        name: forgeservice
        ports:
        - containerPort: 8080
        resources:
          requests:
            cpu: "25m"
      restartPolicy: Always
      serviceAccountName: ""
      volumes: []

