apiVersion: v1
kind: Service
metadata:
  labels:
    service: smelterservice
  name: smelterservice
spec:
  ports:
  - name: "8081"
    port: 8081
    targetPort: 8081
  selector:
    service: smelterservice

